name: design_your_furniture
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
   - assets/
   - assets/images-nobg/
   - assets/images/
  
  fonts:
      - family: CustomIcons
        fonts:
          - asset: assets/fonts/CustomIcons.ttf
  
      - family: Montserrat-Bold
        fonts:
          - asset: assets/fonts/Montserrat-Bold.ttf

      - family: Montserrat-Black
        fonts:
          - asset: assets/fonts/Montserrat-Black.ttf

      - family: Montserrat-Medium
        fonts:
          - asset: assets/fonts/Montserrat-Medium.ttf
