name: minimalist_music_player
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  just_audio: ^0.9.24
  get: ^4.6.5
  just_audio_windows: ^0.1.0
  just_audio_libwinmedia: ^0.0.4
  rive: ^0.9.0
  rxdart: ^0.27.4
  flutter_switch: ^0.3.2
  # rive: ^0.7.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - audios/

  fonts:
    - family: Fascinate-Regular
      fonts: 
        - asset: assets/fonts/Fascinate-Regular.ttf
    - family: AmaticSC-Regular
      fonts: 
        - asset: assets/fonts/AmaticSC-Regular.ttf